### ISSUE TITLE
fget_object raises error when local path has nested directory

### ISSUE THREAD

**Issue by KelvinHong** [oussjarrousse/pytest-minio-mock#31]
The method `MockMinioClient.fget_object` doesn't work as expected when the `file_path` argument has a nested folder structure and doesn't exists.

https://github.com/oussjarrousse/pytest-minio-mock/blob/157693dad9caf505d0e460d59f2c42375875815c/pytest_minio_mock/plugin.py#L818-L864

Expected behavior:
`fget_object` should create the parent directory of `file_path` before attempting to `get_object`.

Also, this is the implementation from `minio-py`

https://github.com/minio/minio-py/blob/fd3571aa9b9402f050192ad4c6c087d2806ca9eb/minio/api.py#L1116

My proposed solution:

Add this line before calling `self.get_object`: 
```python
os.makedirs(os.path.dirname(file_path), exist_ok=True)
```

Let me know what do you think about this! Or is there any reason why `makedirs` is purposely not called?

**Comment by oussjarrousse** [comment]
Thank you for opening the issue, and for the fix suggestion. 
I actually identified several other interface issues with fget_object().
Usually I encourage users to submit a pull request. but this time I am fixing it myself because it is a small issue and I am experimenting with a branching and CI/CD pipline.

Here is the pull request 
https://github.com/oussjarrousse/pytest-minio-mock/pull/32

Let me know if you have any comments.

I will merge it and publish the new version over the weekend.

**Comment by oussjarrousse** [comment]
I just published a new release v0.4.14
https://pypi.org/project/pytest-minio-mock/0.4.14/
closing this issue!
